# =============================================================================
# config/data.py  –  Static configuration: stopwords, difficulty, syllabus,
#                    course list, brain-exercise definitions, school programs
# =============================================================================

STOPWORDS = set("""a about above after again against all also am an and any are aren't as at be because been
before being below between both but by can't cannot could couldn't did didn't do does doesn't doing don't down
during each few for from further get got had hadn't has hasn't have haven't having he he'd he'll he's her here
here's hers herself him himself his how how's i i'd i'll i'm i've if in into is isn't it it's its itself
let's me more most mustn't my myself no nor not of off on once only or other ought our ours ourselves out over
own same shan't she she'd she'll she's should shouldn't so some such than that that's the their theirs them
themselves then there there's these they they'd they'll they're they've this those through to too under until
up very was wasn't we we'd we'll we're we've were weren't what what's when when's where where's which while
who who's whom why why's will with won't would wouldn't you you'd you'll you're you've your yours yourself
yourselves the a is are was were be been being have has had having do does did doing will would shall should
may might must can could""".split())

# ---------------------------------------------------------------------------
# Quiz difficulty settings
# ---------------------------------------------------------------------------
DIFFICULTY_SETTINGS = {
    "Easy":   {"blend": 0.7, "distractors": 2, "bonus_xp": 1.0},
    "Medium": {"blend": 0.5, "distractors": 3, "bonus_xp": 1.5},
    "Hard":   {"blend": 0.3, "distractors": 3, "bonus_xp": 2.0},
}

# ---------------------------------------------------------------------------
# Course syllabus
# ---------------------------------------------------------------------------
COURSE_SYLLABUS = {
    "SEEB1101": {
        "title": "Electrical and Electronics Engineering",
        "description": "Foundations of circuits, semiconductor devices, op-amps and electrical machines.",
        "instructor": "Dr. R. Krishnamurthy", "rating": 4.8, "enrolled": 2340,
        "modules": [
            {"id": 1, "title": "DC Circuits & Network Theorems", "lessons": [
                {"id": "1.1", "title": "Ohm's Law & Kirchhoff's Laws", "duration": "45 min", "type": "video",
                 "notes": "Ohm's Law states V = IR. KVL: sum of voltages in a loop = 0. KCL: sum of currents at a node = 0.",
                 "youtube": "https://www.youtube.com/results?search_query=Ohm%27s+Law+Kirchhoff%27s+Laws",
                 "wiki": "https://en.wikipedia.org/wiki/Kirchhoff%27s_circuit_laws"},
                {"id": "1.2", "title": "Thevenin's & Norton's Theorems", "duration": "50 min", "type": "video",
                 "notes": "Thevenin: Any linear network = Vth in series with Rth. Norton: In in parallel with Rn. Vth = In × Rth.",
                 "youtube": "https://www.youtube.com/results?search_query=Thevenin+Norton+theorem",
                 "wiki": "https://en.wikipedia.org/wiki/Th%C3%A9venin%27s_theorem"},
                {"id": "1.3", "title": "Superposition & Maximum Power Transfer", "duration": "40 min", "type": "reading",
                 "notes": "Superposition: Response = sum of individual source responses. Max power transfer when RL = Rth (efficiency = 50%).",
                 "youtube": "https://www.youtube.com/results?search_query=Superposition+theorem+circuits",
                 "wiki": "https://en.wikipedia.org/wiki/Maximum_power_transfer_theorem"},
                {"id": "1.4", "title": "Practice Problems – Network Analysis", "duration": "30 min", "type": "quiz",
                 "notes": "Apply all theorems: mesh analysis, node voltage, Thevenin equivalent circuits.",
                 "youtube": "https://www.youtube.com/results?search_query=Network+analysis+solved+problems",
                 "wiki": "https://en.wikipedia.org/wiki/Network_analysis_(electrical_circuits)"},
            ]},
            {"id": 2, "title": "AC Circuits & Phasors", "lessons": [
                {"id": "2.1", "title": "Sinusoidal Waveforms & Phasor Representation", "duration": "45 min", "type": "video",
                 "notes": "v(t) = Vm sin(ωt + φ). Phasor: V = Vm∠φ. RMS = Vm/√2. Angular frequency ω = 2πf.",
                 "youtube": "https://www.youtube.com/results?search_query=phasor+representation+AC+circuits",
                 "wiki": "https://en.wikipedia.org/wiki/Phasor"},
                {"id": "2.2", "title": "Impedance, Resonance & Power Factor", "duration": "50 min", "type": "video",
                 "notes": "Z = R + jX. Resonance: XL = XC, ω₀ = 1/√(LC). PF = cos(φ). Unity PF = purely resistive load.",
                 "youtube": "https://www.youtube.com/results?search_query=impedance+resonance+power+factor",
                 "wiki": "https://en.wikipedia.org/wiki/Electrical_impedance"},
                {"id": "2.3", "title": "Three-Phase Systems", "duration": "40 min", "type": "reading",
                 "notes": "Star (Y) and Delta (Δ) connections. Line voltage = √3 × Phase voltage (Star). 3-phase power = √3 × VL × IL × cos(φ).",
                 "youtube": "https://www.youtube.com/results?search_query=three+phase+system+star+delta",
                 "wiki": "https://en.wikipedia.org/wiki/Three-phase_electric_power"},
            ]},
            {"id": 3, "title": "Semiconductor Devices", "lessons": [
                {"id": "3.1", "title": "PN Junction Diode & Applications", "duration": "45 min", "type": "video",
                 "notes": "Depletion region, forward/reverse bias. Shockley: I = I₀(e^(V/VT) - 1). Applications: rectifiers, clippers, clampers.",
                 "youtube": "https://www.youtube.com/results?search_query=PN+junction+diode+working",
                 "wiki": "https://en.wikipedia.org/wiki/P%E2%80%93n_junction"},
                {"id": "3.2", "title": "BJT & FET Transistors", "duration": "55 min", "type": "video",
                 "notes": "BJT: NPN/PNP, CE/CB/CC configs. β = IC/IB. FET: JFET/MOSFET, ID = K(VGS - Vth)².",
                 "youtube": "https://www.youtube.com/results?search_query=BJT+FET+transistor+basics",
                 "wiki": "https://en.wikipedia.org/wiki/Transistor"},
                {"id": "3.3", "title": "Rectifier Circuits & Filters", "duration": "40 min", "type": "reading",
                 "notes": "Half-wave: Vdc = Vm/π. Full-wave: Vdc = 2Vm/π. Bridge rectifier uses 4 diodes.",
                 "youtube": "https://www.youtube.com/results?search_query=rectifier+circuits+filter",
                 "wiki": "https://en.wikipedia.org/wiki/Rectifier"},
                {"id": "3.4", "title": "Quiz: Semiconductor Fundamentals", "duration": "25 min", "type": "quiz",
                 "notes": "Review: diode characteristics, transistor biasing, rectifier design, and filter calculations.",
                 "youtube": "https://www.youtube.com/results?search_query=semiconductor+devices+questions",
                 "wiki": "https://en.wikipedia.org/wiki/Semiconductor_device"},
            ]},
            {"id": 4, "title": "Operational Amplifiers", "lessons": [
                {"id": "4.1", "title": "Ideal Op-Amp Characteristics", "duration": "40 min", "type": "video",
                 "notes": "Infinite input impedance, zero output impedance, infinite gain, infinite bandwidth. Virtual short & virtual open concepts.",
                 "youtube": "https://www.youtube.com/results?search_query=op-amp+ideal+characteristics",
                 "wiki": "https://en.wikipedia.org/wiki/Operational_amplifier"},
                {"id": "4.2", "title": "Inverting, Non-Inverting & Summing Amplifiers", "duration": "45 min", "type": "video",
                 "notes": "Inverting: Av = -Rf/R1. Non-inverting: Av = 1 + Rf/R1. Summing: Vout = -(Rf/R1×V1 + Rf/R2×V2).",
                 "youtube": "https://www.youtube.com/results?search_query=inverting+non-inverting+op-amp",
                 "wiki": "https://en.wikipedia.org/wiki/Operational_amplifier_applications"},
                {"id": "4.3", "title": "Integrators, Differentiators & Comparators", "duration": "40 min", "type": "reading",
                 "notes": "Integrator: Vout = -1/RC ∫Vin dt. Differentiator: Vout = -RC × dVin/dt. Comparator: no feedback.",
                 "youtube": "https://www.youtube.com/results?search_query=op-amp+integrator+differentiator",
                 "wiki": "https://en.wikipedia.org/wiki/Comparator"},
            ]},
            {"id": 5, "title": "Electrical Machines & Power Systems", "lessons": [
                {"id": "5.1", "title": "DC Motors & Generators", "duration": "50 min", "type": "video",
                 "notes": "E = PΦNz/60A. Torque T = PΦIaz/2πA. Speed regulation = (No - Nfl)/Nfl × 100%. Series, shunt, compound motors.",
                 "youtube": "https://www.youtube.com/results?search_query=DC+motor+generator+working",
                 "wiki": "https://en.wikipedia.org/wiki/DC_motor"},
                {"id": "5.2", "title": "Transformers: Principles & Applications", "duration": "45 min", "type": "video",
                 "notes": "V1/V2 = N1/N2 = I2/I1 (turns ratio). Efficiency η = Pout/Pin. Losses: copper (I²R) and core (eddy + hysteresis).",
                 "youtube": "https://www.youtube.com/results?search_query=transformer+working+principle",
                 "wiki": "https://en.wikipedia.org/wiki/Transformer"},
                {"id": "5.3", "title": "Induction Motors & Synchronous Machines", "duration": "50 min", "type": "reading",
                 "notes": "Slip s = (Ns - N)/Ns. Torque ∝ sE2²R2/(R2² + s²X2²). Synchronous speed Ns = 120f/P.",
                 "youtube": "https://www.youtube.com/results?search_query=induction+motor+synchronous+machine",
                 "wiki": "https://en.wikipedia.org/wiki/Induction_motor"},
                {"id": "5.4", "title": "Final Assessment – EEE", "duration": "60 min", "type": "quiz",
                 "notes": "Comprehensive review of all 5 modules. Focus on problem-solving and formula application.",
                 "youtube": "https://www.youtube.com/results?search_query=EEE+exam+preparation",
                 "wiki": "https://en.wikipedia.org/wiki/Electrical_engineering"},
            ]},
        ],
    },
    "S11BLH21": {
        "title": "One Day One Program – Programming",
        "description": "Daily programming challenges from Python basics to data structures, OOP, and project work.",
        "instructor": "Prof. S. Anand", "rating": 4.7, "enrolled": 3100,
        "modules": [
            {"id": 1, "title": "Python Fundamentals", "lessons": [
                {"id": "1.1", "title": "Variables, Data Types & Operators", "duration": "35 min", "type": "video",
                 "notes": "int, float, str, bool, list, tuple, dict, set. Arithmetic: +,-,*,/,//,%,**. Comparison: ==,!=,<,>.",
                 "youtube": "https://www.youtube.com/results?search_query=python+variables+data+types",
                 "wiki": "https://en.wikipedia.org/wiki/Python_(programming_language)"},
                {"id": "1.2", "title": "Control Flow: if/else, loops", "duration": "40 min", "type": "video",
                 "notes": "if/elif/else for branching. for loop: iterate over sequences. while loop: condition-based. break, continue, pass.",
                 "youtube": "https://www.youtube.com/results?search_query=python+control+flow+loops",
                 "wiki": "https://en.wikipedia.org/wiki/Control_flow"},
                {"id": "1.3", "title": "Functions & Recursion", "duration": "45 min", "type": "reading",
                 "notes": "def func(params): return val. *args, **kwargs. Lambda: f = lambda x: x². Recursion: base case + recursive case.",
                 "youtube": "https://www.youtube.com/results?search_query=python+functions+recursion",
                 "wiki": "https://en.wikipedia.org/wiki/Recursion_(computer_science)"},
                {"id": "1.4", "title": "Daily Challenge: Day 1-7 Problems", "duration": "60 min", "type": "quiz",
                 "notes": "FizzBuzz, Fibonacci, factorial, palindrome check, list reversal, prime detection.",
                 "youtube": "https://www.youtube.com/results?search_query=python+beginner+coding+challenges",
                 "wiki": "https://en.wikipedia.org/wiki/FizzBuzz"},
            ]},
            {"id": 2, "title": "Data Structures in Python", "lessons": [
                {"id": "2.1", "title": "Lists, Tuples & Sets", "duration": "40 min", "type": "video",
                 "notes": "List: mutable, ordered. Tuple: immutable, ordered. Set: mutable, unordered, unique.",
                 "youtube": "https://www.youtube.com/results?search_query=python+lists+tuples+sets",
                 "wiki": "https://en.wikipedia.org/wiki/List_(abstract_data_type)"},
                {"id": "2.2", "title": "Dictionaries & HashMaps", "duration": "40 min", "type": "video",
                 "notes": "dict: key-value pairs. O(1) lookup. dict comprehensions. defaultdict, Counter, OrderedDict.",
                 "youtube": "https://www.youtube.com/results?search_query=python+dictionary+hashmap",
                 "wiki": "https://en.wikipedia.org/wiki/Hash_table"},
                {"id": "2.3", "title": "Stacks, Queues & Linked Lists", "duration": "50 min", "type": "reading",
                 "notes": "Stack: LIFO (list.append/pop). Queue: FIFO (collections.deque). Linked List: Node class with next pointer.",
                 "youtube": "https://www.youtube.com/results?search_query=stack+queue+linked+list+python",
                 "wiki": "https://en.wikipedia.org/wiki/Linked_list"},
            ]},
            {"id": 3, "title": "Algorithms & Complexity", "lessons": [
                {"id": "3.1", "title": "Sorting: Bubble, Merge, Quick Sort", "duration": "50 min", "type": "video",
                 "notes": "Bubble: O(n²). Merge: O(n log n), divide & conquer. Quick: avg O(n log n), worst O(n²).",
                 "youtube": "https://www.youtube.com/results?search_query=sorting+algorithms+python",
                 "wiki": "https://en.wikipedia.org/wiki/Sorting_algorithm"},
                {"id": "3.2", "title": "Searching: Linear & Binary Search", "duration": "35 min", "type": "video",
                 "notes": "Linear: O(n). Binary: O(log n), requires sorted array. Bisect module for binary search.",
                 "youtube": "https://www.youtube.com/results?search_query=binary+search+python",
                 "wiki": "https://en.wikipedia.org/wiki/Binary_search_algorithm"},
                {"id": "3.3", "title": "Big-O Notation & Complexity Analysis", "duration": "40 min", "type": "reading",
                 "notes": "O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ). Space complexity. Amortized analysis.",
                 "youtube": "https://www.youtube.com/results?search_query=Big-O+notation+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Big_O_notation"},
                {"id": "3.4", "title": "Algorithm Challenge Set", "duration": "45 min", "type": "quiz",
                 "notes": "Implement merge sort, binary search, detect cycle in linked list, balanced parentheses.",
                 "youtube": "https://www.youtube.com/results?search_query=algorithm+interview+questions+python",
                 "wiki": "https://en.wikipedia.org/wiki/Algorithm"},
            ]},
            {"id": 4, "title": "Object-Oriented Programming", "lessons": [
                {"id": "4.1", "title": "Classes, Objects & Encapsulation", "duration": "45 min", "type": "video",
                 "notes": "__init__, self, instance/class variables. @property decorator. Private: _single, __dunder.",
                 "youtube": "https://www.youtube.com/results?search_query=python+OOP+classes+objects",
                 "wiki": "https://en.wikipedia.org/wiki/Object-oriented_programming"},
                {"id": "4.2", "title": "Inheritance & Polymorphism", "duration": "45 min", "type": "video",
                 "notes": "class Child(Parent): Method overriding, super(). MRO (C3 linearisation). Duck typing. @abstractmethod.",
                 "youtube": "https://www.youtube.com/results?search_query=python+inheritance+polymorphism",
                 "wiki": "https://en.wikipedia.org/wiki/Polymorphism_(computer_science)"},
                {"id": "4.3", "title": "Abstraction & Design Patterns", "duration": "40 min", "type": "reading",
                 "notes": "ABC module for abstract classes. Singleton, Factory, Observer, Strategy patterns. SOLID principles.",
                 "youtube": "https://www.youtube.com/results?search_query=python+design+patterns",
                 "wiki": "https://en.wikipedia.org/wiki/Design_Patterns"},
            ]},
            {"id": 5, "title": "Advanced Python & Projects", "lessons": [
                {"id": "5.1", "title": "File I/O, Exceptions & Modules", "duration": "40 min", "type": "video",
                 "notes": "with open() as f. try/except/finally. Custom exceptions. __name__ == '__main__'. pip, virtual environments.",
                 "youtube": "https://www.youtube.com/results?search_query=python+file+IO+exceptions",
                 "wiki": "https://en.wikipedia.org/wiki/Exception_handling"},
                {"id": "5.2", "title": "Web Scraping & APIs", "duration": "50 min", "type": "video",
                 "notes": "requests.get(), BeautifulSoup. REST APIs: GET/POST/PUT/DELETE. JSON parsing. Rate limiting. robots.txt.",
                 "youtube": "https://www.youtube.com/results?search_query=python+web+scraping+API",
                 "wiki": "https://en.wikipedia.org/wiki/Web_scraping"},
                {"id": "5.3", "title": "Mini Project: Data Analyser", "duration": "90 min", "type": "project",
                 "notes": "Build a CLI data analyser: read CSV, compute stats (mean, median, std), plot with matplotlib, export report.",
                 "youtube": "https://www.youtube.com/results?search_query=python+data+analysis+project",
                 "wiki": "https://en.wikipedia.org/wiki/Data_analysis"},
                {"id": "5.4", "title": "Final Coding Assessment", "duration": "60 min", "type": "quiz",
                 "notes": "All topics: OOP design, data structures, algorithm analysis, file handling, API integration.",
                 "youtube": "https://www.youtube.com/results?search_query=python+advanced+interview+questions",
                 "wiki": "https://en.wikipedia.org/wiki/Python_(programming_language)"},
            ]},
        ],
    },
    "S731BLH32": {
        "title": "Machine Learning Essentials",
        "description": "Core ML algorithms, model evaluation, feature engineering and real-world deployment.",
        "instructor": "Dr. P. Sharma", "rating": 4.9, "enrolled": 4200,
        "modules": [
            {"id": 1, "title": "Introduction to Machine Learning", "lessons": [
                {"id": "1.1", "title": "What is ML? Supervised vs Unsupervised", "duration": "40 min", "type": "video",
                 "notes": "ML: systems that learn from data. Supervised: labeled data. Unsupervised: unlabeled. Reinforcement: reward-based.",
                 "youtube": "https://www.youtube.com/results?search_query=machine+learning+introduction",
                 "wiki": "https://en.wikipedia.org/wiki/Machine_learning"},
                {"id": "1.2", "title": "The ML Pipeline: Data to Deployment", "duration": "45 min", "type": "video",
                 "notes": "Data collection → EDA → Preprocessing → Feature engineering → Model selection → Training → Evaluation → Deployment.",
                 "youtube": "https://www.youtube.com/results?search_query=machine+learning+pipeline",
                 "wiki": "https://en.wikipedia.org/wiki/Machine_learning_pipeline"},
                {"id": "1.3", "title": "Python for ML: NumPy & Pandas", "duration": "50 min", "type": "reading",
                 "notes": "NumPy: ndarray, broadcasting, vectorisation. Pandas: DataFrame, Series, groupby, merge, pivot.",
                 "youtube": "https://www.youtube.com/results?search_query=numpy+pandas+machine+learning",
                 "wiki": "https://en.wikipedia.org/wiki/Pandas_(software)"},
                {"id": "1.4", "title": "Quiz: ML Foundations", "duration": "20 min", "type": "quiz",
                 "notes": "Definitions, pipeline stages, Python libraries, types of learning.",
                 "youtube": "https://www.youtube.com/results?search_query=machine+learning+quiz+questions",
                 "wiki": "https://en.wikipedia.org/wiki/Machine_learning"},
            ]},
            {"id": 2, "title": "Supervised Learning", "lessons": [
                {"id": "2.1", "title": "Linear & Logistic Regression", "duration": "55 min", "type": "video",
                 "notes": "Linear: y = mx + b, MSE loss, gradient descent. Logistic: sigmoid σ(z) = 1/(1+e^-z), log-loss.",
                 "youtube": "https://www.youtube.com/results?search_query=linear+logistic+regression+ML",
                 "wiki": "https://en.wikipedia.org/wiki/Logistic_regression"},
                {"id": "2.2", "title": "Decision Trees & Random Forests", "duration": "55 min", "type": "video",
                 "notes": "DT: Gini impurity / entropy splitting. RF: bagging + feature randomness. Feature importance via MDI.",
                 "youtube": "https://www.youtube.com/results?search_query=decision+tree+random+forest+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Random_forest"},
                {"id": "2.3", "title": "Support Vector Machines", "duration": "50 min", "type": "reading",
                 "notes": "Maximum margin hyperplane. Support vectors. Kernel trick: RBF, polynomial. C and γ parameters.",
                 "youtube": "https://www.youtube.com/results?search_query=SVM+support+vector+machine+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Support_vector_machine"},
                {"id": "2.4", "title": "Lab: Classification with scikit-learn", "duration": "60 min", "type": "project",
                 "notes": "Iris/Titanic dataset. train_test_split, fit, predict, accuracy_score, confusion_matrix.",
                 "youtube": "https://www.youtube.com/results?search_query=scikit-learn+classification+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/Scikit-learn"},
            ]},
            {"id": 3, "title": "Unsupervised Learning", "lessons": [
                {"id": "3.1", "title": "K-Means & Hierarchical Clustering", "duration": "50 min", "type": "video",
                 "notes": "K-Means: assign to nearest centroid, recompute centroids. Elbow method for k. Dendrogram, linkage.",
                 "youtube": "https://www.youtube.com/results?search_query=k-means+clustering+explained",
                 "wiki": "https://en.wikipedia.org/wiki/K-means_clustering"},
                {"id": "3.2", "title": "PCA & Dimensionality Reduction", "duration": "50 min", "type": "video",
                 "notes": "PCA: eigenvectors of covariance matrix. Explained variance ratio. t-SNE for visualisation.",
                 "youtube": "https://www.youtube.com/results?search_query=PCA+dimensionality+reduction",
                 "wiki": "https://en.wikipedia.org/wiki/Principal_component_analysis"},
                {"id": "3.3", "title": "Anomaly Detection", "duration": "40 min", "type": "reading",
                 "notes": "Isolation Forest, One-Class SVM, LOF. Z-score and IQR methods. Applications: fraud, intrusion detection.",
                 "youtube": "https://www.youtube.com/results?search_query=anomaly+detection+machine+learning",
                 "wiki": "https://en.wikipedia.org/wiki/Anomaly_detection"},
            ]},
            {"id": 4, "title": "Model Evaluation & Tuning", "lessons": [
                {"id": "4.1", "title": "Train/Test Split, Cross-Validation", "duration": "45 min", "type": "video",
                 "notes": "80/20 or 70/30 split. k-fold CV: train on k-1 folds. Stratified CV for imbalanced. Leave-One-Out CV.",
                 "youtube": "https://www.youtube.com/results?search_query=cross+validation+sklearn",
                 "wiki": "https://en.wikipedia.org/wiki/Cross-validation_(statistics)"},
                {"id": "4.2", "title": "Bias-Variance Tradeoff & Overfitting", "duration": "45 min", "type": "video",
                 "notes": "High bias = underfitting. High variance = overfitting. Regularisation: L1 (Lasso), L2 (Ridge).",
                 "youtube": "https://www.youtube.com/results?search_query=bias+variance+tradeoff",
                 "wiki": "https://en.wikipedia.org/wiki/Bias%E2%80%93variance_tradeoff"},
                {"id": "4.3", "title": "Hyperparameter Tuning", "duration": "40 min", "type": "reading",
                 "notes": "GridSearchCV: exhaustive. RandomizedSearchCV: faster. Bayesian optimisation: Optuna. Early stopping.",
                 "youtube": "https://www.youtube.com/results?search_query=hyperparameter+tuning+sklearn",
                 "wiki": "https://en.wikipedia.org/wiki/Hyperparameter_optimization"},
            ]},
            {"id": 5, "title": "Deep Learning & Deployment", "lessons": [
                {"id": "5.1", "title": "Neural Networks: Perceptron to MLP", "duration": "60 min", "type": "video",
                 "notes": "Perceptron: wx + b, step activation. MLP: hidden layers, ReLU/sigmoid/tanh. Backprop: chain rule.",
                 "youtube": "https://www.youtube.com/results?search_query=neural+network+MLP+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Multilayer_perceptron"},
                {"id": "5.2", "title": "Intro to TensorFlow / PyTorch", "duration": "55 min", "type": "video",
                 "notes": "TF: tf.keras Sequential API. PyTorch: nn.Module, autograd. Dataset, DataLoader. Adam optimizer.",
                 "youtube": "https://www.youtube.com/results?search_query=tensorflow+pytorch+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/TensorFlow"},
                {"id": "5.3", "title": "Model Deployment with Flask & Streamlit", "duration": "50 min", "type": "reading",
                 "notes": "pickle/joblib for model serialisation. Flask REST API: /predict endpoint. Docker containerisation.",
                 "youtube": "https://www.youtube.com/results?search_query=ML+model+deployment+flask+streamlit",
                 "wiki": "https://en.wikipedia.org/wiki/Flask_(web_framework)"},
                {"id": "5.4", "title": "Capstone: End-to-End ML Project", "duration": "90 min", "type": "project",
                 "notes": "Full pipeline: dataset → EDA → preprocessing → model training → evaluation → Streamlit dashboard.",
                 "youtube": "https://www.youtube.com/results?search_query=end+to+end+ML+project",
                 "wiki": "https://en.wikipedia.org/wiki/Machine_learning"},
            ]},
        ],
    },
    "S731BLH51": {
        "title": "Big Data Analytics for AI",
        "description": "Hadoop, Spark, data lakes, Kafka streaming and scalable AI pipelines.",
        "instructor": "Dr. K. Ramesh", "rating": 4.6, "enrolled": 1850,
        "modules": [
            {"id": 1, "title": "Big Data Fundamentals", "lessons": [
                {"id": "1.1", "title": "The 5 Vs of Big Data", "duration": "35 min", "type": "video",
                 "notes": "Volume (scale), Velocity (speed), Variety (types), Veracity (accuracy), Value (insights).",
                 "youtube": "https://www.youtube.com/results?search_query=5Vs+big+data+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Big_data"},
                {"id": "1.2", "title": "Batch vs Stream Processing", "duration": "40 min", "type": "video",
                 "notes": "Batch: process large stored datasets (Hadoop MapReduce). Stream: process data in motion (Kafka + Flink).",
                 "youtube": "https://www.youtube.com/results?search_query=batch+vs+stream+processing",
                 "wiki": "https://en.wikipedia.org/wiki/Stream_processing"},
                {"id": "1.3", "title": "Hadoop Ecosystem Overview", "duration": "45 min", "type": "reading",
                 "notes": "HDFS (storage), MapReduce (processing), YARN (resource mgmt), Hive (SQL), HBase (NoSQL), Oozie.",
                 "youtube": "https://www.youtube.com/results?search_query=Hadoop+ecosystem+overview",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Hadoop"},
                {"id": "1.4", "title": "Quiz: Big Data Concepts", "duration": "20 min", "type": "quiz",
                 "notes": "5 Vs, Hadoop components, CAP theorem, comparison of processing paradigms.",
                 "youtube": "https://www.youtube.com/results?search_query=big+data+interview+questions",
                 "wiki": "https://en.wikipedia.org/wiki/Big_data"},
            ]},
            {"id": 2, "title": "Apache Spark", "lessons": [
                {"id": "2.1", "title": "Spark Architecture & RDDs", "duration": "55 min", "type": "video",
                 "notes": "Driver + Executors. RDD: immutable distributed collection. Transformations (lazy) vs Actions (eager).",
                 "youtube": "https://www.youtube.com/results?search_query=Apache+Spark+RDD+architecture",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Spark"},
                {"id": "2.2", "title": "Spark DataFrames & SQL", "duration": "55 min", "type": "video",
                 "notes": "spark.read.csv/json/parquet. DataFrame API: filter, groupBy, agg, join. Catalyst optimiser.",
                 "youtube": "https://www.youtube.com/results?search_query=Spark+DataFrame+SQL+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Spark"},
                {"id": "2.3", "title": "Spark MLlib for Machine Learning", "duration": "50 min", "type": "reading",
                 "notes": "Pipeline API: Transformer + Estimator. Algorithms: LR, RF, k-means, ALS. CrossValidator.",
                 "youtube": "https://www.youtube.com/results?search_query=Spark+MLlib+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Spark"},
                {"id": "2.4", "title": "Lab: Spark Transformations", "duration": "60 min", "type": "project",
                 "notes": "PySpark: load 1M record CSV, run groupBy aggregations, build classification pipeline.",
                 "youtube": "https://www.youtube.com/results?search_query=PySpark+tutorial+beginners",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Spark"},
            ]},
            {"id": 3, "title": "Data Warehousing & Lakes", "lessons": [
                {"id": "3.1", "title": "Data Warehouse vs Data Lake vs Lakehouse", "duration": "45 min", "type": "video",
                 "notes": "DW: structured, schema-on-write. Lake: raw data, schema-on-read. Lakehouse (Delta Lake): ACID on lake.",
                 "youtube": "https://www.youtube.com/results?search_query=data+warehouse+lake+lakehouse",
                 "wiki": "https://en.wikipedia.org/wiki/Data_lake"},
                {"id": "3.2", "title": "ETL/ELT Pipelines", "duration": "50 min", "type": "video",
                 "notes": "ETL: Extract → Transform → Load (traditional). ELT: cloud-native. Apache Airflow for orchestration.",
                 "youtube": "https://www.youtube.com/results?search_query=ETL+ELT+pipeline+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Extract,_transform,_load"},
                {"id": "3.3", "title": "Delta Lake & Apache Iceberg", "duration": "40 min", "type": "reading",
                 "notes": "Delta Lake: ACID transactions, time travel, schema enforcement. Iceberg: partition evolution.",
                 "youtube": "https://www.youtube.com/results?search_query=Delta+Lake+Apache+Iceberg",
                 "wiki": "https://en.wikipedia.org/wiki/Delta_Lake"},
            ]},
            {"id": 4, "title": "Real-Time Analytics", "lessons": [
                {"id": "4.1", "title": "Apache Kafka: Event Streaming", "duration": "55 min", "type": "video",
                 "notes": "Producer → Topic (Partitions) → Consumer Group. Offset management. Replication factor.",
                 "youtube": "https://www.youtube.com/results?search_query=Apache+Kafka+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Kafka"},
                {"id": "4.2", "title": "Apache Flink & Stream Processing", "duration": "50 min", "type": "video",
                 "notes": "Dataflow model. Event time vs processing time. Watermarks. Windows: tumbling, sliding, session.",
                 "youtube": "https://www.youtube.com/results?search_query=Apache+Flink+stream+processing",
                 "wiki": "https://en.wikipedia.org/wiki/Apache_Flink"},
                {"id": "4.3", "title": "Real-Time Dashboards with Plotly", "duration": "40 min", "type": "reading",
                 "notes": "Plotly Dash: dcc.Graph, callback decorators, @app.callback. Streaming updates with dcc.Interval.",
                 "youtube": "https://www.youtube.com/results?search_query=plotly+dash+real+time+dashboard",
                 "wiki": "https://en.wikipedia.org/wiki/Plotly"},
            ]},
            {"id": 5, "title": "Cloud & AI at Scale", "lessons": [
                {"id": "5.1", "title": "AWS / Azure / GCP for Big Data", "duration": "55 min", "type": "video",
                 "notes": "AWS: S3, Glue, EMR, Redshift, Athena. Azure: ADLS, Synapse, Databricks. GCP: BigQuery, Dataflow.",
                 "youtube": "https://www.youtube.com/results?search_query=AWS+Azure+GCP+big+data+comparison",
                 "wiki": "https://en.wikipedia.org/wiki/Cloud_computing"},
                {"id": "5.2", "title": "AutoML & AI Platforms", "duration": "50 min", "type": "video",
                 "notes": "AutoML: automated feature engineering, model selection. Platforms: H2O.ai, Google AutoML, TPOT.",
                 "youtube": "https://www.youtube.com/results?search_query=AutoML+explained+platforms",
                 "wiki": "https://en.wikipedia.org/wiki/Automated_machine_learning"},
                {"id": "5.3", "title": "Scalable ML Deployment with Kubernetes", "duration": "45 min", "type": "reading",
                 "notes": "Docker: containerise model. Kubernetes: Pod, Deployment, Service, Ingress. MLflow for tracking.",
                 "youtube": "https://www.youtube.com/results?search_query=ML+deployment+kubernetes+docker",
                 "wiki": "https://en.wikipedia.org/wiki/Kubernetes"},
                {"id": "5.4", "title": "Final Project: Analytics Pipeline", "duration": "90 min", "type": "project",
                 "notes": "End-to-end: Kafka producer → Spark Streaming → Delta Lake → Plotly dashboard.",
                 "youtube": "https://www.youtube.com/results?search_query=real+time+analytics+pipeline+project",
                 "wiki": "https://en.wikipedia.org/wiki/Big_data"},
            ]},
        ],
    },
    "SCSB1351": {
        "title": "Algorithms for Intelligent Systems",
        "description": "Advanced algorithms powering search, optimisation, game AI and neural network training.",
        "instructor": "Prof. A. Venkatesh", "rating": 4.7, "enrolled": 2900,
        "modules": [
            {"id": 1, "title": "Foundations of Algorithm Design", "lessons": [
                {"id": "1.1", "title": "Divide & Conquer Paradigm", "duration": "45 min", "type": "video",
                 "notes": "Divide problem → Conquer subproblems → Combine. Merge sort T(n)=2T(n/2)+O(n). Master theorem.",
                 "youtube": "https://www.youtube.com/results?search_query=divide+and+conquer+algorithms",
                 "wiki": "https://en.wikipedia.org/wiki/Divide-and-conquer_algorithm"},
                {"id": "1.2", "title": "Dynamic Programming: Memoization & Tabulation", "duration": "60 min", "type": "video",
                 "notes": "DP: optimal substructure + overlapping subproblems. Examples: Fibonacci, 0/1 Knapsack, LCS, LIS.",
                 "youtube": "https://www.youtube.com/results?search_query=dynamic+programming+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Dynamic_programming"},
                {"id": "1.3", "title": "Greedy Algorithms & Proofs", "duration": "45 min", "type": "reading",
                 "notes": "Greedy choice property + optimal substructure. Activity selection, Huffman coding, Dijkstra, Kruskal.",
                 "youtube": "https://www.youtube.com/results?search_query=greedy+algorithms+examples",
                 "wiki": "https://en.wikipedia.org/wiki/Greedy_algorithm"},
                {"id": "1.4", "title": "Quiz: Algorithm Paradigms", "duration": "25 min", "type": "quiz",
                 "notes": "Identify paradigm for given problem, recurrence relations, DP table construction.",
                 "youtube": "https://www.youtube.com/results?search_query=algorithm+paradigms+quiz",
                 "wiki": "https://en.wikipedia.org/wiki/Algorithm"},
            ]},
            {"id": 2, "title": "Graph Algorithms", "lessons": [
                {"id": "2.1", "title": "BFS, DFS & Topological Sort", "duration": "50 min", "type": "video",
                 "notes": "BFS: queue, O(V+E), shortest path (unweighted). DFS: stack/recursion, cycle detection.",
                 "youtube": "https://www.youtube.com/results?search_query=BFS+DFS+topological+sort",
                 "wiki": "https://en.wikipedia.org/wiki/Breadth-first_search"},
                {"id": "2.2", "title": "Dijkstra's & Bellman-Ford", "duration": "55 min", "type": "video",
                 "notes": "Dijkstra: priority queue, O((V+E)log V). Bellman-Ford: O(VE), handles neg weights.",
                 "youtube": "https://www.youtube.com/results?search_query=Dijkstra+Bellman-Ford+algorithm",
                 "wiki": "https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm"},
                {"id": "2.3", "title": "Minimum Spanning Trees: Prim & Kruskal", "duration": "50 min", "type": "reading",
                 "notes": "Prim: grow tree greedily from source. Kruskal: sort edges, union-find, O(E log E).",
                 "youtube": "https://www.youtube.com/results?search_query=Prim+Kruskal+MST+algorithm",
                 "wiki": "https://en.wikipedia.org/wiki/Minimum_spanning_tree"},
            ]},
            {"id": 3, "title": "Search & Optimisation", "lessons": [
                {"id": "3.1", "title": "A* Search & Heuristics", "duration": "55 min", "type": "video",
                 "notes": "f(n) = g(n) + h(n). Admissible heuristic: h(n) ≤ actual cost. Manhattan distance for grids.",
                 "youtube": "https://www.youtube.com/results?search_query=A+star+search+algorithm",
                 "wiki": "https://en.wikipedia.org/wiki/A*_search_algorithm"},
                {"id": "3.2", "title": "Genetic Algorithms & Evolutionary Computation", "duration": "50 min", "type": "video",
                 "notes": "Population → Selection → Crossover → Mutation → Evaluate fitness. Encoding: binary, real, permutation.",
                 "youtube": "https://www.youtube.com/results?search_query=genetic+algorithm+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Genetic_algorithm"},
                {"id": "3.3", "title": "Simulated Annealing & Swarm Intelligence", "duration": "45 min", "type": "reading",
                 "notes": "SA: accept worse solution with P = e^(-ΔE/T). PSO: particles update velocity/position. ACO: pheromone.",
                 "youtube": "https://www.youtube.com/results?search_query=simulated+annealing+particle+swarm",
                 "wiki": "https://en.wikipedia.org/wiki/Simulated_annealing"},
            ]},
            {"id": 4, "title": "NP-Completeness & Complexity", "lessons": [
                {"id": "4.1", "title": "P vs NP Problem", "duration": "50 min", "type": "video",
                 "notes": "P: solvable in polynomial time. NP: verifiable in polynomial time. NP-complete: hardest in NP.",
                 "youtube": "https://www.youtube.com/results?search_query=P+vs+NP+explained",
                 "wiki": "https://en.wikipedia.org/wiki/P_versus_NP_problem"},
                {"id": "4.2", "title": "NP-Hard Problems & Reductions", "duration": "55 min", "type": "video",
                 "notes": "Reduction: A ≤p B. SAT (Cook-Levin theorem). 3-SAT, Clique, Vertex Cover, Hamiltonian Cycle.",
                 "youtube": "https://www.youtube.com/results?search_query=NP-complete+reductions+explained",
                 "wiki": "https://en.wikipedia.org/wiki/NP-completeness"},
                {"id": "4.3", "title": "Approximation Algorithms", "duration": "45 min", "type": "reading",
                 "notes": "ρ-approximation: ALG ≤ ρ × OPT. Vertex cover: 2-approx. TSP metric: Christofides 1.5-approx.",
                 "youtube": "https://www.youtube.com/results?search_query=approximation+algorithms+NP",
                 "wiki": "https://en.wikipedia.org/wiki/Approximation_algorithm"},
            ]},
            {"id": 5, "title": "AI-Specific Algorithms", "lessons": [
                {"id": "5.1", "title": "Minimax & Alpha-Beta Pruning", "duration": "55 min", "type": "video",
                 "notes": "Minimax: MAX player maximises, MIN minimises. Alpha-beta: prune branches where α ≥ β.",
                 "youtube": "https://www.youtube.com/results?search_query=minimax+alpha+beta+pruning",
                 "wiki": "https://en.wikipedia.org/wiki/Alpha%E2%80%93beta_pruning"},
                {"id": "5.2", "title": "Monte Carlo Tree Search (MCTS)", "duration": "50 min", "type": "video",
                 "notes": "Selection (UCT) → Expansion → Simulation (rollout) → Backpropagation. Used in AlphaGo.",
                 "youtube": "https://www.youtube.com/results?search_query=Monte+Carlo+Tree+Search+MCTS",
                 "wiki": "https://en.wikipedia.org/wiki/Monte_Carlo_tree_search"},
                {"id": "5.3", "title": "Backpropagation in Neural Networks", "duration": "55 min", "type": "reading",
                 "notes": "Forward pass → compute loss → backward pass via chain rule. Vanishing gradient: ReLU, BatchNorm.",
                 "youtube": "https://www.youtube.com/results?search_query=backpropagation+neural+network+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Backpropagation"},
                {"id": "5.4", "title": "Final Algorithm Design Challenge", "duration": "75 min", "type": "quiz",
                 "notes": "Design A* for robot navigation, implement minimax for Tic-Tac-Toe, DP for optimal scheduling.",
                 "youtube": "https://www.youtube.com/results?search_query=advanced+algorithm+problems",
                 "wiki": "https://en.wikipedia.org/wiki/Algorithm"},
            ]},
        ],
    },
    "SCSB1501": {
        "title": "Data Communication & Networks",
        "description": "OSI/TCP-IP models, routing, wireless, security and cloud networking.",
        "instructor": "Dr. M. Subramaniam", "rating": 4.5, "enrolled": 2600,
        "modules": [
            {"id": 1, "title": "Network Fundamentals", "lessons": [
                {"id": "1.1", "title": "OSI Model & TCP/IP Stack", "duration": "45 min", "type": "video",
                 "notes": "OSI 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application. TCP/IP 4 layers.",
                 "youtube": "https://www.youtube.com/results?search_query=OSI+model+TCP+IP+explained",
                 "wiki": "https://en.wikipedia.org/wiki/OSI_model"},
                {"id": "1.2", "title": "Network Topologies & Media Types", "duration": "40 min", "type": "video",
                 "notes": "Bus, Star, Ring, Mesh, Hybrid topologies. Guided: UTP, STP, coaxial, fiber. Unguided: radio, microwave.",
                 "youtube": "https://www.youtube.com/results?search_query=network+topologies+media+types",
                 "wiki": "https://en.wikipedia.org/wiki/Network_topology"},
                {"id": "1.3", "title": "IP Addressing & Subnetting", "duration": "55 min", "type": "reading",
                 "notes": "IPv4: 32-bit, CIDR notation. Subnet mask, network/host bits. VLSM. IPv6: 128-bit, 8 groups of 4 hex.",
                 "youtube": "https://www.youtube.com/results?search_query=IP+addressing+subnetting+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/IP_address"},
                {"id": "1.4", "title": "Quiz: Networking Fundamentals", "duration": "20 min", "type": "quiz",
                 "notes": "OSI layers, subnetting calculations, media characteristics, topology comparisons.",
                 "youtube": "https://www.youtube.com/results?search_query=networking+fundamentals+quiz",
                 "wiki": "https://en.wikipedia.org/wiki/Computer_network"},
            ]},
            {"id": 2, "title": "Data Link & Physical Layer", "lessons": [
                {"id": "2.1", "title": "Ethernet, MAC Addresses & Switching", "duration": "45 min", "type": "video",
                 "notes": "Ethernet frame: preamble, dest/src MAC, type, data, FCS. MAC: 48-bit. Switch: MAC table, flooding.",
                 "youtube": "https://www.youtube.com/results?search_query=ethernet+MAC+switching+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Ethernet"},
                {"id": "2.2", "title": "Error Detection: CRC, Hamming", "duration": "45 min", "type": "video",
                 "notes": "Parity: even/odd. CRC: polynomial division. Hamming: corrects 1 bit, detects 2. r check bits.",
                 "youtube": "https://www.youtube.com/results?search_query=CRC+Hamming+code+error+detection",
                 "wiki": "https://en.wikipedia.org/wiki/Cyclic_redundancy_check"},
                {"id": "2.3", "title": "Wireless: WiFi, Bluetooth & 5G", "duration": "45 min", "type": "reading",
                 "notes": "WiFi 802.11ax (Wi-Fi 6): OFDMA, MU-MIMO. BT 5.3: 2.4 GHz. 5G: sub-6 GHz + mmWave, 20 Gbps.",
                 "youtube": "https://www.youtube.com/results?search_query=WiFi+Bluetooth+5G+explained",
                 "wiki": "https://en.wikipedia.org/wiki/5G"},
            ]},
            {"id": 3, "title": "Network Layer & Routing", "lessons": [
                {"id": "3.1", "title": "Routing Algorithms: RIP, OSPF, BGP", "duration": "55 min", "type": "video",
                 "notes": "RIP: distance vector, hop count ≤ 15. OSPF: link state, Dijkstra, areas. BGP: path vector, inter-AS.",
                 "youtube": "https://www.youtube.com/results?search_query=RIP+OSPF+BGP+routing+protocol",
                 "wiki": "https://en.wikipedia.org/wiki/Routing_protocol"},
                {"id": "3.2", "title": "VLAN, NAT & DHCP", "duration": "50 min", "type": "video",
                 "notes": "VLAN: 802.1Q tag, logical segmentation. NAT: private IP → public IP, PAT. DHCP: DORA, lease time.",
                 "youtube": "https://www.youtube.com/results?search_query=VLAN+NAT+DHCP+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Virtual_LAN"},
                {"id": "3.3", "title": "Software-Defined Networking (SDN)", "duration": "45 min", "type": "reading",
                 "notes": "Control plane (SDN controller) separated from data plane. OpenFlow protocol. NFV.",
                 "youtube": "https://www.youtube.com/results?search_query=SDN+software+defined+networking",
                 "wiki": "https://en.wikipedia.org/wiki/Software-defined_networking"},
            ]},
            {"id": 4, "title": "Transport & Application Layer", "lessons": [
                {"id": "4.1", "title": "TCP vs UDP: Reliability & Flow Control", "duration": "50 min", "type": "video",
                 "notes": "TCP: 3-way handshake (SYN/SYN-ACK/ACK), reliable, ordered, congestion control (AIMD).",
                 "youtube": "https://www.youtube.com/results?search_query=TCP+UDP+comparison+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Transmission_Control_Protocol"},
                {"id": "4.2", "title": "HTTP/HTTPS, DNS & SMTP", "duration": "45 min", "type": "video",
                 "notes": "HTTP/2: multiplexing, header compression. HTTPS: TLS 1.3. DNS: recursive/iterative. SMTP: 25/587.",
                 "youtube": "https://www.youtube.com/results?search_query=HTTP+DNS+SMTP+protocols",
                 "wiki": "https://en.wikipedia.org/wiki/HTTP"},
                {"id": "4.3", "title": "REST APIs & WebSockets", "duration": "40 min", "type": "reading",
                 "notes": "REST: stateless, CRUD → HTTP verbs, JSON. WebSocket: full-duplex, ws:// port 80. GraphQL vs REST.",
                 "youtube": "https://www.youtube.com/results?search_query=REST+API+WebSocket+tutorial",
                 "wiki": "https://en.wikipedia.org/wiki/WebSocket"},
            ]},
            {"id": 5, "title": "Network Security & Cloud", "lessons": [
                {"id": "5.1", "title": "Firewalls, IDS/IPS & VPNs", "duration": "55 min", "type": "video",
                 "notes": "Firewall: packet filter, stateful, next-gen (NGFW). IDS: signature/anomaly. VPN: IPsec, OpenVPN, WireGuard.",
                 "youtube": "https://www.youtube.com/results?search_query=firewall+IDS+IPS+VPN+explained",
                 "wiki": "https://en.wikipedia.org/wiki/Firewall_(computing)"},
                {"id": "5.2", "title": "Cryptography: SSL/TLS & PKI", "duration": "50 min", "type": "video",
                 "notes": "Symmetric: AES-256. Asymmetric: RSA-2048, ECC. TLS 1.3: 1-RTT, forward secrecy. PKI: CA, X.509.",
                 "youtube": "https://www.youtube.com/results?search_query=SSL+TLS+PKI+cryptography",
                 "wiki": "https://en.wikipedia.org/wiki/Transport_Layer_Security"},
                {"id": "5.3", "title": "Cloud Networking: AWS VPC, Azure VNet", "duration": "45 min", "type": "reading",
                 "notes": "VPC: subnets (public/private), route tables, IGW, NAT gateway, security groups, NACLs.",
                 "youtube": "https://www.youtube.com/results?search_query=AWS+VPC+Azure+VNet+networking",
                 "wiki": "https://en.wikipedia.org/wiki/Amazon_Virtual_Private_Cloud"},
                {"id": "5.4", "title": "Network Design Capstone", "duration": "75 min", "type": "project",
                 "notes": "Design enterprise network: HQ + 2 branches, redundant ISP links, OSPF, VLANs, DMZ, VPN tunnels.",
                 "youtube": "https://www.youtube.com/results?search_query=enterprise+network+design+project",
                 "wiki": "https://en.wikipedia.org/wiki/Computer_network"},
            ]},
        ],
    },
}

# ---------------------------------------------------------------------------
# Course list (UI cards)
# ---------------------------------------------------------------------------
COURSES = [
    {"code": "SEEB1101",  "title": "Electrical and Electronics Engineering", "term": "Even Semester", "bg": "linear-gradient(135deg,#1e3a8a,#3b82f6)"},
    {"code": "S11BLH21",  "title": "One Day One Program – Programming",      "term": "Semester 2",    "bg": "linear-gradient(135deg,#7c3aed,#a78bfa)"},
    {"code": "S731BLH32", "title": "Machine Learning Essentials",            "term": "Even Semester", "bg": "linear-gradient(135deg,#be123c,#fb7185)"},
    {"code": "S731BLH51", "title": "Big Data Analytics for AI",              "term": "Odd Semester",  "bg": "linear-gradient(135deg,#0284c7,#38bdf8)"},
    {"code": "SCSB1351",  "title": "Algorithms for Intelligent Systems",      "term": "Odd Semester",  "bg": "linear-gradient(135deg,#0f172a,#334155)"},
    {"code": "SCSB1501",  "title": "Data Communication & Networks",          "term": "Semester 5",    "bg": "linear-gradient(135deg,#b45309,#fbbf24)"},
]

# ---------------------------------------------------------------------------
# Brain-training exercise definitions
# ---------------------------------------------------------------------------
BRAIN_EX = [
    {"id": "math",   "title": "Synaptic Sequencing",    "subtitle": "Mathematical Subjects",
     "desc": "Upload Calculus, Algebra, Data Structures, or any math-heavy material.",
     "icon": "🔢", "xp": 150, "bg": "linear-gradient(135deg,#1d4ed8,#06b6d4)", "color": "#2563eb",
     "fmts": ["pdf", "docx", "pptx", "txt"]},
    {"id": "theory", "title": "Stroop Effect Override", "subtitle": "Theory Subjects",
     "desc": "Master concepts, history, literature, and humanities material.",
     "icon": "🎨", "xp": 100, "bg": "linear-gradient(135deg,#be185d,#f43f5e)", "color": "#be185d",
     "fmts": ["pdf", "docx", "txt", "pptx"]},
    {"id": "coding", "title": "Spatial Matrix Logic",   "subtitle": "Coding Subjects",
     "desc": "Upload scripts, algorithms, and logic structures for code analysis.",
     "icon": "🔷", "xp": 250, "bg": "linear-gradient(135deg,#7c3aed,#6366f1)", "color": "#7c3aed",
     "fmts": ["py", "js", "cpp", "txt", "pdf"]},
]

# ---------------------------------------------------------------------------
# Schools & programs (registration form)
# ---------------------------------------------------------------------------
SCHOOLS_PROGRAMS = {
    "School of Computing":            ["B.E CSE (General)", "B.E CSE - AI", "B.E CSE - AIML",
                                       "B.E CSE - DS", "B.E CSE - CS", "B.E CSE - IoT",
                                       "B.E CSE - BCT", "B.Tech IT"],
    "School of Science & Humanities": ["B.Sc Physics", "B.Sc Mathematics", "M.Sc Psychology"],
    "School of EEE":                  ["B.Tech EEE", "B.Tech ECE", "B.Tech Embedded Systems"],
    "School of Mechanical":           ["B.Tech Mechanical", "B.Tech Mechatronics", "B.Tech Aeronautical"],
    "School of Management":           ["B.B.A.", "M.B.A. Finance & HR", "M.B.A. Operations & Marketing"],
}

# ---------------------------------------------------------------------------
# Default users (demo credential)
# ---------------------------------------------------------------------------
USERS_DB = {
    "43611162": {
        "name": "Karre John Hyde", "password": "pass", "degree": "Undergraduate",
        "year": "1st Year", "school": "School of Computing", "program": "B.E CSE (General)",
    }
}
